/*

    Copyright (C) 2004 Michael Liebscher <johnnycanuck@users.sourceforge.net>
    Copyright (C) 1997-2001 Id Software, Inc.

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

/**
 * @file client_main.c
 * @brief Client main loop.
 * @author Michael Liebscher
 * @date 2004
 * @author Id Software, Inc.
 * @date 1997-2001
 */

#include <stdio.h>

#include "client.h"
#include "keys.h"
#include "video.h"
#include "timer.h"
#include "input.h"
#include "com_string.h"

cvar_t  *sensitivity;
cvar_t  *m_yaw;
cvar_t  *m_forward;
cvar_t  *name;

client_state_t  ClientState;
client_static_t ClientStatic;


/**
 * Disconnect the client from the server.
 * @note Called after an ERR_DROP was thrown.
 */
PUBLIC void Client_Drop (void)
{
}
#include "../wolf/wolf_local.h"
/**
 * Console command to disconnect client from server.
 */
PUBLIC void Client_Quit_f (void)
{
    Game_Shutdown();
    Sys_Quit();
}

/**
 * Initialize client variables and commands.
 */
PRIVATE void Client_InitLocal (void)
{
    //ClientStatic.state = ca_disconnected;
    ClientStatic.realtime = Sys_Milliseconds();

    cl_forwardspeed = Cvar_Get ("cl_forwardspeed", "4000", CVAR_INIT);
    cl_sidespeed    = Cvar_Get ("cl_sidespeed", "4000", CVAR_INIT);
    cl_yawspeed     = Cvar_Get ("cl_yawspeed", "100", CVAR_INIT);

    sensitivity = Cvar_Get ("m_sensitivity", "50", CVAR_ARCHIVE);

    m_yaw   = Cvar_Get ("m_yaw", "1", CVAR_INIT);
    m_forward = Cvar_Get ("m_forward", "1", CVAR_INIT);

//
// register our commands
//
}

/**
 * Initialize Client sub-systems.
 * @return Initialize video and sound sub-systems.
 */
PUBLIC void Client_Init (void)
{
    Video_Init();
    //Sound_Init();

    Menu_Init();

    Client_InitLocal();
    IN_Init();
}

/**
 * Writes key bindings and archived cvars to config.cfg.
 */
PRIVATE void Client_WriteConfiguration (void)
{
    FILE    *fp;
    char    path[ MAX_OSPATH];

    com_snprintf (path, sizeof (path), "%s/config.cfg", FS_Gamedir());
    fp = fopen (path, "w");

    if (!fp) {
        return;
    }

    fprintf (fp, "// Generated by %s, do not modify!\n", GAME_NAME);
    Key_WriteBindings (fp);

    Cvar_WriteVariables (fp);

    fclose (fp);
}

/**
 * Shutdown client sub-systems.
 */
PUBLIC void Client_Shutdown (void)
{
    static _boolean isdown = false;

    if (isdown) {
        return;
    }
    isdown = true;

    Client_WriteConfiguration();

    IN_Shutdown();
    Video_Shutdown();
}
