/*

    Copyright (C) 2004 Michael Liebscher <johnnycanuck@users.sourceforge.net>
    Copyright (C) 1997-2001 Id Software, Inc.

    This program is free software; you can redistribute it and/or
    modify it under the terms of the GNU General Public License
    as published by the Free Software Foundation; either version 2
    of the License, or (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

*/

/**
 * @file client_main.c
 * @brief Client main loop.
 * @author Michael Liebscher
 * @date 2004
 * @author Id Software, Inc.
 * @date 1997-2001
 */

#include <stdio.h>

#include "client.h"
#include "console.h"
#include "keys.h"
#include "video.h"
#include "timer.h"
#include "input.h"
#include "com_string.h"
#include "sound.h"

cvar_t  *freelook;

cvar_t  *lookspring;
cvar_t  *lookstrafe;
cvar_t  *sensitivity;

cvar_t  *m_pitch;
cvar_t  *m_yaw;
cvar_t  *m_forward;
cvar_t  *m_side;


cvar_t  *name;

client_state_t  ClientState;
client_static_t ClientStatic;


/**
 * Disconnect the client from the server.
 * @note Called after an ERR_DROP was thrown.
 */
PUBLIC void Client_Drop (void)
{
}

/**
 * Console command to disconnect client from server.
 */
PUBLIC void Client_Quit_f (void)
{
    Com_Quit();
}

/**
 * Initialize client variables and commands.
 */
PRIVATE void Client_InitLocal (void)
{
    ClientStatic.state = ca_disconnected;
    ClientStatic.realtime = Sys_Milliseconds();

    Client_InitInput();

    cl_forwardspeed = Cvar_Get ("cl_forwardspeed", "4000", CVAR_INIT);
    cl_sidespeed    = Cvar_Get ("cl_sidespeed", "4000", CVAR_INIT);
    cl_yawspeed     = Cvar_Get ("cl_yawspeed", "100", CVAR_INIT);
    cl_pitchspeed   = Cvar_Get ("cl_pitchspeed", "100", CVAR_INIT);
    cl_anglespeedkey = Cvar_Get ("cl_anglespeedkey", "2", CVAR_INIT);

    cl_run      = Cvar_Get ("cl_run", "0", CVAR_ARCHIVE);
    freelook    = Cvar_Get ("freelook", "0", CVAR_ARCHIVE);
    lookspring  = Cvar_Get ("lookspring", "0", CVAR_ARCHIVE);
    lookstrafe  = Cvar_Get ("lookstrafe", "0", CVAR_ARCHIVE);
    sensitivity = Cvar_Get ("m_sensitivity", "300", CVAR_ARCHIVE);

    m_pitch = Cvar_Get ("m_pitch", "0.022", CVAR_ARCHIVE);
    m_yaw   = Cvar_Get ("m_yaw", "1", CVAR_INIT);
    m_side  = Cvar_Get ("m_side", "1", CVAR_INIT);
    m_forward = Cvar_Get ("m_forward", "1", CVAR_INIT);

//
// register our commands
//
    Cmd_AddCommand ("quit", Client_Quit_f);
}

/**
 * Initialize Client sub-systems.
 * @return Initialize video and sound sub-systems.
 */
PUBLIC void Client_Init (void)
{
    if (dedicated->value)
        return;     // nothing running on the client

    Con_Init();

    Video_Init();
    Sound_Init();   // sound must be initialized after window is created

    Menu_Init();

    Client_Screen_Init();
    Client_InitLocal();
    IN_Init();
}

/**
 * Writes key bindings and archived cvars to config.cfg.
 */
PRIVATE void Client_WriteConfiguration (void)
{
    FILE    *fp;
    char    path[ MAX_OSPATH];

    if (ClientStatic.state == ca_uninitialized) {
        return;
    }

    com_snprintf (path, sizeof (path), "%s/config.cfg", FS_Gamedir());
    fp = fopen (path, "w");

    if (!fp) {
        return;
    }

    fprintf (fp, "// Generated by %s, do not modify!\n", GAME_NAME);
    Key_WriteBindings (fp);

    Cvar_WriteVariables (fp);

    fclose (fp);
}

/**
 * Shutdown client sub-systems.
 */
PUBLIC void Client_Shutdown (void)
{
    static _boolean isdown = false;

    if (isdown) {
        return;
    }
    isdown = true;

    Client_WriteConfiguration();

    Sound_Shutdown();
    IN_Shutdown();
    Video_Shutdown();
}
